(source gnu)

;; load from melpa-stable -----

(source melpa-stable)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "cider")
(depends-on "company")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "emmet-mode")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-clojure")
(depends-on "flycheck-pos-tip")
(depends-on "git-timemachine")
(depends-on "go-mode")
(depends-on "golden-ratio")
(depends-on "gotham-theme")
(depends-on "helm")
(depends-on "helm-dash")
(depends-on "idle-highlight-mode")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "paredit")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "protobuf-mode")
(depends-on "rainbow-delimiters")
(depends-on "s")
(depends-on "scss-mode")
(depends-on "smart-mode-line")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "whitespace")
(depends-on "writeroom-mode")
(depends-on "yaml-mode")
(depends-on "yasnippet")

;; load from master -----

(depends-on "package-build" :git "https://github.com/milkypostman/melpa" :ref "master")
(depends-on "pallet" :git "https://github.com/rdallasgray/pallet" :ref "master")

;; load from melpa-unstable -----

(source melpa)
(depends-on "htmlize")
(depends-on "ox-reveal")
(depends-on "paren-face")
